# ==============================================================================
# Module manifest for module 'PS.GitHub'
# Generated by: Justin Johns
# Generated on: 2026-07-02
# ==============================================================================

@{
    # Script module or binary module file associated with this manifest.
    RootModule           = 'PS.GitHub.psm1'

    # Version number of this module.
    # Major = significant changes, breaking changes or major new features
    # Minor = new functions or features
    # Build = bug fixes and minor updates
    ModuleVersion        = '0.1.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID                 = '7e2bf01c-b962-4b87-aa58-415058ecfb10'

    # Author of this module
    Author               = 'Justin Johns'

    # Copyright statement for this module
    Copyright            = '(c) 2026 Justin Johns. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Portable PowerShell helpers wrapping the gh CLI and GitHub REST API. Targets stateful side-effect mistakes that author-time guidance cannot prevent: temp-body-file hygiene, missing OAuth scopes surfacing as opaque 404s, and tag-object-vs-commit-SHA confusion when pinning GitHub Actions.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.4'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @()

    # Functions to export from this module. Populated per-PR as functions land.
    # v0.1.0 target: Invoke-GhApi, New-GhBody, Test-GhAuthScope, Resolve-GhCommitSha
    FunctionsToExport    = @(
        'Invoke-GhApi'
        'New-GhBody'
        'Resolve-GhCommitSha'
        'Test-GhAuthScope'
    )

    # Cmdlets to export from this module
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module
    AliasesToExport      = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    PrivateData          = @{

        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('GitHub', 'gh', 'REST', 'API', 'Automation', 'DevOps')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/johnsarie27/PS.GitHub/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/johnsarie27/PS.GitHub'

            # ReleaseNotes of this module
            ReleaseNotes = @'
v0.1.0 - Initial release. Ships four public functions:
  * Invoke-GhApi        - gh api wrapper with pagination, silent-404, empty-204 short-circuit
  * New-GhBody          - ScriptBlock wrapper that owns temp body file lifecycle end-to-end
  * Test-GhAuthScope    - gh auth status preflight; throws with concrete remediation on miss
  * Resolve-GhCommitSha - tag/branch/SHA -> commit SHA (avoids annotated-tag-object trap)

Also ships one private helper (Invoke-Gh) that enforces preference isolation
and string[] boundary normalization structurally. Tag-only release; not
published to PSGallery in v0.1.0.
'@

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}
